---
title: "Binomial_GLM_Model"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
# Load necessary packages
library(here)
library(tidyverse)
library(lubridate)
library(nlme)
library(gtsummary)
library(DHARMa)
library(lme4)
library(dplyr)
library(lmerTest)
library(sjPlot)
library(plotly)
library(car)
library(moments)

#load data
bleaching_all <- read.csv("Code/global_bleaching_environmental.csv")

# filtering bleaching data for area of interest (aoi)
bleaching_aoi <- bleaching_all %>% 
  filter(Ecoregion_Name == "Bahamas and Florida Keys")

#convert to numeric
bleaching_aoi$Percent_Bleaching <- as.numeric(parse_number(bleaching_aoi$Percent_Bleaching))
bleaching_aoi$Temperature_Mean <- as.numeric(parse_number(bleaching_aoi$Temperature_Mean))
bleaching_aoi$Turbidity <- as.numeric(parse_number(bleaching_aoi$Turbidity))
bleaching_aoi$Distance_to_Shore <- as.numeric(parse_number(bleaching_aoi$Distance_to_Shore))
bleaching_aoi$Depth_m <- as.numeric(parse_number(bleaching_aoi$Depth_m))

#drop na
bleaching_aoi <- bleaching_aoi %>% 
  drop_na()

#convert percent bleaching
bleaching_aoi <- bleaching_aoi %>% 
  mutate(pct_bleaching = Percent_Bleaching/100)

#group by site ID
bleaching_aoi_grouped <- bleaching_aoi %>% 
  group_by(Site_ID) %>% 
  summarise(mean_pct_bleach = mean(pct_bleaching, na.rm = TRUE),
            mean_temp = mean(Temperature_Mean, na.rm = TRUE),
            mean_turbidity = mean(Turbidity, na.rm = TRUE),
            mean_cyclone = mean(Cyclone_Frequency, na.rm = TRUE),
            mean_distance_to_shore = mean(Distance_to_Shore, na.rm = TRUE),
            mean_depth = mean(Depth_m, na.rm = TRUE)) %>% 
  mutate(mean_temp_c = mean_temp - 273.15)

# setting threshold for mass bleaching
bleaching_aoi_grouped <- bleaching_aoi_grouped %>% 
  mutate(pct_bleaching_50 = ifelse(mean_pct_bleach >=0.5, 1, 0)) %>% 
  mutate(pct_bleaching_25 = ifelse(mean_pct_bleach >=0.25, 1, 0))


```

```{r}
# data exploration
histo_temp <- ggplot(bleaching_aoi_grouped, aes(x = mean_temp_c)) +
  geom_histogram(fill = "deepskyblue3") +
  labs(x = "Temperature (°C)",
       y = "Count")
histo_temp

histo_turbidity <- ggplot(bleaching_aoi_grouped, aes(x = mean_turbidity)) +
  geom_histogram(fill = "deepskyblue3") +
  labs(x = "Turbidity",
       y = "Count")
histo_turbidity

histo_cyclone <- ggplot(bleaching_aoi_grouped, aes(x = mean_cyclone)) +
  geom_histogram(fill = "deepskyblue3") +
  labs(x = "Cyclone Frequency",
       y = "Count")
histo_cyclone

histo_distance <- ggplot(bleaching_aoi_grouped, aes(x = mean_distance_to_shore)) +
  geom_histogram(fill = "deepskyblue3") +
  labs(x = "Distance to Shore (m) ",
       y = "Count")
histo_distance

histo_depth <- ggplot(bleaching_aoi_grouped, aes(x = mean_depth)) +
  geom_histogram(fill = "deepskyblue3") +
  labs(x = "Depth (m) ",
       y = "Count")
histo_depth

histo_mass_bleach <- ggplot(bleaching_aoi_grouped, aes(x = pct_bleaching_50)) +
  geom_bar(fill = "deepskyblue3") +
  labs(x = "Mass Bleaching Presence",
       y = "Count")
histo_mass_bleach

scatter_temp <- ggplot(bleaching_aoi_grouped, aes(x = mean_temp_c, y = pct_bleaching_50)) +
  geom_boxplot(color = "deepskyblue4") +
  labs(x = "Temperature (°C)",
       y = "Mass Bleaching Presence") 
scatter_temp

scatter_cyclone <- ggplot(bleaching_aoi_grouped, aes(x = mean_cyclone, y = pct_bleaching_50)) +
  geom_boxplot(color = "deepskyblue4") +
  labs(x = "Cyclone Frequency",
       y = "Mass Bleaching Presence")
scatter_cyclone

scatter_turbidity <- ggplot(bleaching_aoi_grouped, aes(x = mean_turbidity, y = pct_bleaching_50)) +
  geom_boxplot(color = "deepskyblue4") +
  labs(x = "Turbidity",
       y = "Mass Bleaching Presence")
scatter_turbidity

# understanding how the 0s affect our linear relationship
bleaching_aoi_grouped %>% 
filter(mean_pct_bleach !=0) %>% 
ggplot(aes(x = mean_temp_c, y = mean_pct_bleach))+
  geom_point()+
  geom_smooth(method = "lm")

```

```{r}
# Histogram for presentation
histograms <- (histo_mass_bleach + histo_temp) / (histo_cyclone + histo_turbidity)  
 # plot_annotation(
 # title = "Distributions of Each Covariate Relevant to Coral Bleaching")
histograms

# Scatters
scatterplots <- scatter_temp + scatter_turbidity + scatter_cyclone
scatterplots
```


```{r}
# Check for multi-collinearity
cor.test(bleaching_aoi_grouped$pct_bleaching_50, bleaching_aoi_grouped$mean_temp_c) # not correlated
cor.test(bleaching_aoi_grouped$pct_bleaching_50, bleaching_aoi_grouped$mean_turbidity) # not correlated
cor.test(bleaching_aoi_grouped$pct_bleaching_50, bleaching_aoi_grouped$mean_cyclone) # not correlated
cor.test(bleaching_aoi_grouped$pct_bleaching_50, bleaching_aoi_grouped$mean_distance_to_shore) # not correlated
cor.test(bleaching_aoi_grouped$pct_bleaching_50, bleaching_aoi_grouped$mean_depth) # not correlated

cor.test(bleaching_aoi_grouped$mean_temp, bleaching_aoi_grouped$mean_turbidity) # not correlated
cor.test(bleaching_aoi_grouped$mean_temp, bleaching_aoi_grouped$mean_cyclone) # not correlated
cor.test(bleaching_aoi_grouped$mean_temp, bleaching_aoi_grouped$mean_distance_to_shore) # not correlated
cor.test(bleaching_aoi_grouped$mean_temp, bleaching_aoi_grouped$mean_depth) # not correlated

cor.test(bleaching_aoi_grouped$mean_turbidity, bleaching_aoi_grouped$mean_cyclone) # not correlated
cor.test(bleaching_aoi_grouped$mean_turbidity, bleaching_aoi_grouped$mean_distance_to_shore) # not correlated
cor.test(bleaching_aoi_grouped$mean_turbidity, bleaching_aoi_grouped$mean_depth) # not correlated

cor.test(bleaching_aoi_grouped$mean_cyclone, bleaching_aoi_grouped$mean_distance_to_shore) # not correlated
cor.test(bleaching_aoi_grouped$mean_cyclone, bleaching_aoi_grouped$mean_depth) # not correlated

cor.test(bleaching_aoi_grouped$mean_distance_to_shore,
         bleaching_aoi_grouped$mean_depth) # not correlated
```


```{r}

# fit logistic regression model
#in this part of the code, if we remove depth / distance to shore, the results would look slightly different
# so feel free to play around with the different variables
bleaching_aoi_grouped$pct_bleaching_50 <- factor(bleaching_aoi_grouped$pct_bleaching_50,
  levels = c(0, 1))

bleaching_binomial_model <- glm(pct_bleaching_50 ~ mean_temp_c  + mean_cyclone + mean_turbidity,
                        family = binomial, 
                        data = bleaching_aoi_grouped)
summary(bleaching_binomial_model)
AIC(bleaching_binomial_model)
simulateResiduals(bleaching_binomial_model) %>% 
  plot()
```


```{r}

# Plot predictions
# Helpful website: https://statsandr.com/blog/binary-logistic-regression-in-r/
plot_model(bleaching_binomial_model, title = "",
  type = "pred",
  terms = "mean_temp_c") +
  labs(x = "Temperature (°C)",
    y = "Probability of Mass Bleaching")

plot_model(bleaching_binomial_model, title = "",
           type = "pred",
           terms = "mean_turbidity") +
  labs(x = "Turbidity",
       y = "Probability of Mass Bleaching")
```

```{r}
# trying to get rid of the 0s
bleaching_aoi_n0 <-bleaching_aoi_grouped %>% 
  filter(mean_pct_bleach !=0)%>% 
  mutate(mean_pct_bleach_log = log10(mean_pct_bleach+0.001))

#check for normality before moving on
skewness(bleaching_aoi_n0$mean_pct_bleach_log)
kurtosis(bleaching_aoi_n0$mean_pct_bleach_log)

#also plot out the data distribution
plot2 <- ggplot(aes(x=mean_pct_bleach_log), data = bleaching_aoi_n0)+
  geom_histogram(fill = "blue4") +
  labs(x = "Log Percent Bleaching",
       y = "Count")
plot2

# plot relationship between covariates and bleaching
scatter_temp_n0 <- ggplot(bleaching_aoi_n0, aes(x = mean_temp_c, y = mean_pct_bleach_log)) +
  geom_point(color = "deepskyblue4") +
  labs(x = "Temperature (°C)",
       y = "Log Percent Bleaching") 
scatter_temp_n0

scatter_cyclone_n0 <- ggplot(bleaching_aoi_n0, aes(x = mean_cyclone, y = mean_pct_bleach_log)) +
  geom_point(color = "deepskyblue4") +
  labs(x = "Cyclone Frequency",
       y = "Log Percent Bleaching")
scatter_cyclone_n0

scatter_turbidity_n0 <- ggplot(bleaching_aoi_n0, aes(x = mean_turbidity, y = mean_pct_bleach_log)) +
  geom_point(color = "deepskyblue4") +
  labs(x = "Turbidity",
       y = "Log Percent Bleaching")
scatter_turbidity_n0

scatter_distance_n0 <- ggplot(bleaching_aoi_n0, aes(x = mean_distance_to_shore, y = mean_pct_bleach_log)) +
  geom_point(color = "deepskyblue4") +
  labs(x = "Distance to shore (m)",
       y = "Log Percent Bleaching")
scatter_distance_n0

relationships <- (scatter_temp_n0 + scatter_turbidity_n0) / (scatter_cyclone_n0 + scatter_distance_n0)
relationships

```

```{r}
# linear regression for just percentage
bleaching_linear_model <- lm(mean_pct_bleach_log ~ mean_temp + mean_cyclone + mean_turbidity + mean_distance_to_shore,
                        data = bleaching_aoi_n0)

summary(bleaching_linear_model)
AIC(bleaching_linear_model)
plot_model(bleaching_linear_model)

#linear regression for maybe mass bleaching threshold??
mass_bleaching_linear_model <- lm(pct_bleaching_50 ~ mean_temp + mean_cyclone + mean_turbidity,
                        data = bleaching_aoi_n0)

summary(mass_bleaching_linear_model)
plot(mass_bleaching_linear_model)
# actually maybe not because the plots look awful

```

