---
title: Initial Data Visualization
author: "Carina Huang, Evan Mularo, Tallulah Bowden"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

# Setup
```{r load packages, message=F, warning=F}
# Load necessary packages
library(here)
library(tidyverse)
library(ggplot2)
library(readr)
library(scrutiny)
library(patchwork)


# Load dataset
bleaching <- read.csv("Code/bahamas_florida_bleaching_subset.csv")
bleaching$Percent_Bleaching <- as.numeric(parse_number(bleaching$Percent_Bleaching))
bleaching$Temperature_Mean <- as.numeric(parse_number(bleaching$Temperature_Mean))
bleaching$Turbidity <- as.numeric(parse_number(bleaching$Turbidity))
bleaching$Distance_to_Shore <- as.numeric(parse_number(bleaching$Distance_to_Shore))

bleaching_combine <- bleaching %>% 
  group_by(Site_ID) %>% 
  summarise(mean_pct_bleach = mean(Percent_Bleaching, na.rm = TRUE),
            mean_temp = mean(Temperature_Mean, na.rm = TRUE),
            mean_turbidity = mean(Turbidity, na.rm = TRUE),
            mean_cyclone = mean(Cyclone_Frequency, na.rm = TRUE),
            mean_distance_to_shore = mean(Distance_to_Shore, na.rm = TRUE)) %>% 
  mutate(pct_beaching = mean_pct_bleach/100) %>% 
  mutate(mean_pct_bleaching_log = log10(pct_beaching + 0.001)) %>%
  drop_na()
#log transform bleaching pct
```

```{r starting plots, message=F, warning=F}
# Histograms
hist_bleaching <- ggplot(bleaching_combine, aes(x = mean_pct_bleaching_log)) +
  geom_histogram(fill = "deepskyblue3") +
  labs(x = "Log Percent Bleaching",
       y = "Count")
hist_bleaching

hist_bleaching1 <- ggplot(bleaching_combine, aes(x = pct_beaching)) +
  geom_histogram(fill = "deepskyblue3") +
  labs(x = "Percent Bleaching",
       y = "Count")
hist_bleaching1

hist_temp <- ggplot(bleaching_combine, aes(x = mean_temp)) +
  geom_histogram(fill = "deepskyblue3") +
  labs(x = "Mean Temperature (K)",
       y = "Count")
hist_temp

hist_turbidity <- ggplot(bleaching_combine, aes(x = mean_turbidity)) +
  geom_histogram(fill = "deepskyblue3") +
  labs(y = "Count")
hist_turbidity

hist_cyclone <- ggplot(bleaching_combine, aes(x = mean_cyclone)) +
  geom_histogram(fill = "deepskyblue3")+
  labs(x = "Cyclone Frequency in Past 50 Years",
       y = "Count")
hist_cyclone

hist_dist_to_shore <- ggplot(bleaching_combine, aes(x = mean_distance_to_shore)) +
  geom_histogram(fill = "deepskyblue3") +
  labs(x = "Distance to Shore (m)",
       y = "Count")
hist_dist_to_shore

# Scatter plots
scatter_distance_to_shore <- ggplot(bleaching_combine, aes(x = mean_distance_to_shore,
                                                   y = mean_pct_bleaching_log)) +
  geom_point(color = "deepskyblue3", alpha = 0.5) +
  labs(x = "Distance to Shore (m)",
       y = "Log Percent Bleaching")
scatter_distance_to_shore

scatter_turbidity <- ggplot(bleaching_combine, aes(x = mean_turbidity,
                                           y = mean_pct_bleaching_log)) +
  geom_point(color = "deepskyblue3", alpha = 0.5) +
  labs(y = "Log Percent Bleaching",
       x = "Turbidity")
scatter_turbidity
scatter_temp <- ggplot(bleaching_combine, aes(x = mean_temp,
                                      y = mean_pct_bleaching_log)) +
  geom_point(color = "deepskyblue3", alpha = 0.5) +
  labs(x = "Mean Temperature (K)",
       y = "Log Percent Bleaching")
scatter_temp

scatter_cyclone <- ggplot(bleaching_combine, aes(x = mean_cyclone,
                                         y = mean_pct_bleaching_log)) +
  geom_point(color = "deepskyblue3", alpha = 0.5) +
  labs(x = "Cyclone Frequency in Past 50 Years",
       y = "Log Percent Bleaching")
scatter_cyclone

# Multi-collinearity
cor.test(bleaching_combine$mean_pct_bleaching_log, bleaching_combine$mean_temp) # not correlated
cor.test(bleaching_combine$mean_pct_bleaching_log, bleaching_combine$mean_turbidity) # not correlated
cor.test(bleaching_combine$mean_pct_bleaching_log, bleaching_combine$mean_cyclone) # not correlated
cor.test(bleaching_combine$mean_pct_bleaching_log, bleaching_combine$mean_distance_to_shore) # not correlated

cor.test(bleaching_combine$mean_temp, bleaching_combine$mean_turbidity) # not correlated
cor.test(bleaching_combine$mean_temp, bleaching_combine$mean_cyclone) # not correlated
cor.test(bleaching_combine$mean_temp, bleaching_combine$mean_distance_to_shore) # not correlated

cor.test(bleaching_combine$mean_turbidity, bleaching_combine$mean_cyclone) # not correlated
cor.test(bleaching_combine$mean_turbidity, bleaching_combine$mean_distance_to_shore) # not correlated

cor.test(bleaching_combine$mean_cyclone, bleaching_combine$mean_distance_to_shore) # not correlated

```

# Notes from Clay
# percent data: look into GLM family that people use. probably not binomial. gaussian?
# Add spatial component. could be used to add categorical variable

```{r figures to submit, message=F, warning=F}
# Histograms
histograms <- (hist_bleaching1 + hist_temp + hist_turbidity) / (hist_cyclone + hist_dist_to_shore) + 
  plot_annotation(
  title = "Distributions of Each Covariate Relevant to Coral Bleaching")
histograms

# Scatters
scatterplots <- (scatter_temp + scatter_turbidity) / (scatter_cyclone + scatter_distance_to_shore) +
  plot_annotation(
    title = "Relationship Between Covariates and Percent Bleaching")
scatterplots
```

