---
title: Mixed Model
authors: "Carina Huang, Evan Mularo, and Tallulah Bowden"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

# Setup

```{r}
# Load necessary packages
library(here)
library(tidyverse)
library(lubridate)
library(nlme)
library(gtsummary)
library(DHARMa)
library(lme4)
library(dplyr)
library(lmerTest)
library(sjPlot)
library(plotly)
library(car)


# Load necessary data
bleaching <- read.csv("Code/bahamas_florida_bleaching_subset.csv")
bleaching$Percent_Bleaching <- as.numeric(parse_number(bleaching$Percent_Bleaching))
bleaching$Temperature_Mean <- as.numeric(parse_number(bleaching$Temperature_Mean))
bleaching$Turbidity <- as.numeric(parse_number(bleaching$Turbidity))
bleaching$Distance_to_Shore <- as.numeric(parse_number(bleaching$Distance_to_Shore))

# Get rid of rows with NAs
bleaching <- bleaching %>%
  drop_na()

# Make percent coral bleaching appropriate for binomial regression
bleaching <- bleaching %>%
  mutate(Bleaching_pct = Percent_Bleaching/100) %>% 
  mutate(Bleaching_pct_log = log10(Bleaching_pct + 0.001)) #log transform bleaching pct

bleaching_combine <- bleaching %>% 
  group_by(Site_ID) %>% 
  summarise(mean_pct_bleach = mean(Percent_Bleaching, na.rm = TRUE),
            mean_temp = mean(Temperature_Mean, na.rm = TRUE),
            mean_turbidity = mean(Turbidity, na.rm = TRUE),
            mean_cyclone = mean(Cyclone_Frequency, na.rm = TRUE),
            mean_distance_to_shore = mean(Distance_to_Shore, na.rm = TRUE)) %>% 
  mutate(pct_beaching = mean_pct_bleach/100) %>% 
  mutate(mean_pct_bleaching_log = log10(pct_beaching + 0.001))  #log transform bleaching pct 

# Visualize the log transformed percent bleaching cover. still not normally distributed
plot1 <- ggplot(aes(x=mean_pct_bleaching_log), data = bleaching_combine)+
  geom_histogram()
plot1


```

```{r}
# trying to get rid of the 0 results and fitting the model again
bleaching_2 <-bleaching_combine %>% 
  filter(mean_pct_bleach !=0)
plot2 <- ggplot(aes(x=mean_pct_bleaching_log), data = bleaching_2)+
  geom_histogram()
plot2

#linear regression model
bleaching_model_log3 <- lm(mean_pct_bleaching_log ~ mean_temp + mean_turbidity + mean_cyclone + mean_distance_to_shore,
                        data = bleaching_2)
AIC(bleaching_model_log3)
summary(bleaching_model_log3)
plot(bleaching_model_log3)
```

### Step 1: Define your research question.

### Do sea surface temperature, distance to shore, turbidity, cyclone events, percent coral bleaching, and site ID significantly predict percent cover of coral bleaching?

### Step 3: Fit linear regression model without random effect and evaluate model diagnostics

```{r}
# Fit linear regression model

bleaching_model1 <- lm(pct_beaching ~ mean_temp + mean_turbidity + mean_cyclone + mean_distance_to_shore,
                        data = bleaching_combine)

bleaching_model_log <- lm(mean_pct_bleaching_log ~ mean_temp + mean_turbidity + mean_cyclone + mean_distance_to_shore,
                        data = bleaching_combine)
AIC(bleaching_model1)
AIC(bleaching_model_log)

# Examine the results and residuals
summary(bleaching_model1)
summary(bleaching_model_log)
plot(bleaching_model1)
plot(bleaching_model_log)

```

### THIS WAS STUFF WITH THE MIXED MODEL

```{r}
# Re-fit standard linear regression
bleaching_model2 <- gls(Bleaching_pct_log ~ Temperature_Mean + Turbidity + Cyclone_Frequency + Distance_to_Shore, 
                        data = bleaching)

# Fit a mixed effects model with random (varying) intercept by plot

bleaching_mixedm1 <- lmer(Bleaching_pct_log ~ Temperature_Mean + Turbidity + Cyclone_Frequency + Distance_to_Shore + (1|Site_ID),
                          data = bleaching,
                          REML = FALSE,
                          control = lmerControl(autoscale = TRUE), bleaching)

# Compare the two model structures
AIC(bleaching_model2, bleaching_mixedm1)

# Examine model residual plot
plot(bleaching_mixedm1)

# Need to examine QQ plot separately
qqnorm(bleaching_mixedm1)

# Examine model results
summary(bleaching_mixedm1) 

```

```{r}
bleaching_mixedm1 <- lmer(Bleaching_pct ~ Temperature_Mean + Turbidity + Cyclone_Frequency + Distance_to_Shore + (1|Site_ID),
                          data = bleaching, 
                          REML = TRUE)
```


# Visualize

```{r}
# Plot coefficients with variation
plot_model(bleaching_model_log, show.values = T,
           title = "Model Coefficients for Covariates Describing Log Percent Bleaching",
           axis.labels = c("Distance to Shore (m)", "Cyclone Number", "Turbidity", "Temperature (K)"))

# 3D plot with cyclone and distance to shore
plot_ly(bleaching_combine, x = ~mean_temp, y = ~mean_cyclone, z = ~mean_pct_bleaching_log, type = "scatter3d", mode = "markers", alpha = 0.7)

# Added variable plots
avPlots(bleaching_model_log)

# Make table with results
tbl_regression(bleaching_model_log)
```

